name: Integration Tests

env:
  ANALYTICS_API_QAR_USERNAME_SERIAL: ${{ secrets.ANALYTICS_API_QAR_USERNAME_SERIAL }}
  ANALYTICS_API_QAR_PASSWORD: ${{ secrets.ANALYTICS_API_QAR_PASSWORD }}

  ANALYTICS_API_USERNAME_SERIAL: ${{ secrets.ANALYTICS_API_USERNAME_SERIAL }}
  ANALYTICS_API_PASSWORD: ${{ secrets.ANALYTICS_API_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      Ref:
        description: 'name of the tag to checkout. Can be "4.0.0" or "v4.2.0" or "5.1.0"'
        required: true
        default: 4.0.0

jobs:
  run-integration-tests-400:
    runs-on: ubuntu-latest
    if: github.event.inputs.Ref == '4.0.0'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '4.0.0'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Build and install new SDK
        run: |
          python -m pip install --upgrade pip
          cd fds.analyticsapi.engines
          python setup.py sdist
          pip install .
      - name: Build and Run Test
        run: |
          cd Utilities/tests
          if [ -f requirements.txt ]
          then
            pip install -r requirements.txt
          fi
          python -m unittest discover
  run-integration-tests-v420:
    runs-on: ubuntu-latest
    if: github.event.inputs.Ref == 'v4.2.0'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'v4.2.0'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Build and install new SDK
        run: |
          python -m pip install --upgrade pip
          cd auto-generated-sdk
          python setup.py sdist
          pip install .
      - name: Build and Run Test
        run: |
          cd tests
          if [ -f requirements.txt ]
          then
            pip install -r requirements.txt
          fi
          python -m unittest discover
  run-integration-tests-v510:
    runs-on: ubuntu-latest
    if: github.event.inputs.Ref == 'v5.1.0'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'v5.1.0'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Build and install new SDK
        run: |
          python -m pip install --upgrade pip
          cd auto-generated-sdk
          python setup.py sdist
          pip install .
      - name: Build and Run Test
        run: |
          cd tests
          if [ -f requirements.txt ]
          then
            pip install -r requirements.txt
          fi
          python -m unittest discover