name: Integration Tests

env:
  ANALYTICS_API_QAR_USERNAME_SERIAL: ${{ secrets.ANALYTICS_API_QAR_USERNAME_SERIAL }}
  ANALYTICS_API_QAR_PASSWORD: ${{ secrets.ANALYTICS_API_QAR_PASSWORD }}

  ANALYTICS_API_USERNAME_SERIAL: ${{ secrets.ANALYTICS_API_USERNAME_SERIAL }}
  ANALYTICS_API_PASSWORD: ${{ secrets.ANALYTICS_API_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      Ref:
        description: 'name of the tag to checkout'
        required: true
        default: 4.0.0

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.Ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Build and install new SDK
        run: |
          python -m pip install --upgrade pip
          cd fds.analyticsapi.engines
          python setup.py sdist
          pip install .
      - name: Build and Run Test
        run: |
          cd Utilities/tests
          if [ -f requirements.txt ]
          then
            pip install -r requirements.txt
          fi
          python -m unittest discover
